// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chgpkpxwtksapjjwvfgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZ3BrcHh3dGtzYXBqand2ZmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDcxMDYsImV4cCI6MjA2NTA4MzEwNn0.nuaCN5CsIAd9sPOOOgMxzpT10Av87qlBTf2AkKWuVb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);